"""deleted user promo and user shows

Revision ID: 6a191e5f804b
Revises: 36d80e6467ba
Create Date: 2023-06-16 15:44:32.582180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a191e5f804b'
down_revision = '36d80e6467ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_promotions')
    op.drop_table('user_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_shows',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('show_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name='fk_user_shows_show_id_shows'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_shows_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_promotions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('promotion_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], name='fk_user_promotions_promotion_id_promotions'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_promotions_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
